<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cloudProvisioning" nsURI="http://cen5064/group1/cloudProvisioning"
    nsPrefix="edu.fiu.cen5064.group1.cloudProvisioning">
  <eClassifiers xsi:type="ecore:EClass" name="Canvas">
    <eStructuralFeatures xsi:type="ecore:EReference" name="environments" upperBound="-1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Instance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="env0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Instance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumVCPUs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CPUSize" eType="#//CPUSize"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NetworkPerformance" eType="#//NetworkPerformance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Memory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Storage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OperatingSystem" eType="#//OperatingSystem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Architecture" eType="#//Architecture"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Applications" upperBound="-1"
        eType="#//Application"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatingSystem">
    <eLiterals name="WindowsServer2008"/>
    <eLiterals name="WindowServer2012"/>
    <eLiterals name="Ubuntu12_04_3"/>
    <eLiterals name="Ubuntu13_10"/>
    <eLiterals name="RHEL6_5"/>
    <eLiterals name="SUSE11"/>
    <eLiterals name="Windows7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Architecture">
    <eLiterals name="x86" literal="x86"/>
    <eLiterals name="x86_64"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NetworkPerformance">
    <eLiterals name="VeryLow"/>
    <eLiterals name="Low"/>
    <eLiterals name="Moderate"/>
    <eLiterals name="High"/>
    <eLiterals name="TenGigabit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Application">
    <eLiterals name="SqlServer2008"/>
    <eLiterals name="MySQL"/>
    <eLiterals name="VisualStudio2012"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CPUSize">
    <eLiterals name="Small"/>
    <eLiterals name="Medium"/>
    <eLiterals name="Large"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Template">
    <eLiterals name="Linux_64_2_32_7_5_H"/>
    <eLiterals name="Windows_64_8_68_8_H"/>
  </eClassifiers>
</ecore:EPackage>
