<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CPmodeling" nsURI="http:///CPmodeling.ecore" nsPrefix="CPmodeling">
  <eClassifiers xsi:type="ecore:EClass" name="environment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vMs" upperBound="-1" eType="#//virtualMachine"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cPUs" upperBound="-1" eType="#//processor"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rAMs" upperBound="-1" eType="#//mainMemory"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mainMemory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="processor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="virtualMachine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vMs" upperBound="-1" eType="#//virtualMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cPUs" upperBound="-1" eType="#//processor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rAMs" upperBound="-1" eType="#//mainMemory"/>
  </eClassifiers>
</ecore:EPackage>
